name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CloudyDayisToday/Linux_Drivers@v2.1.0
        with:
          sources: "./**.h,./**.c,./**.*"